### ISSUE TITLE
Gabage completions after `..` or `...`

### ISSUE THREAD

**Issue by netjune** [mdempsky/gocode#112]
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?
1.11

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/jun/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/jun/Projects/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build824953038=/t
mp/go-build -gno-record-gcc-switches"

### What is the debug output of `gocode`?

Run `gocode close` and then run `gocode -s -debug` to restart gocode in debug mode. 
Try to complete once again from your editor, and paste the output printed by gocode here.

### What editor are using?
Emacs + company-go

**Comment by netjune** [comment]
These completions are unused and unexpected.

**Comment by stamblerre** [comment]
This sounds like an issue with company-go or Emacs, and since the company-go plugin was copied from the original version of [`gocode`](https://github.com/nsf/gocode), I will not be able to make any improvements. Any PRs are welcome. For a better Go autocompletion experience, I would suggest using [`gopls`](https://pkg.go.dev/golang.org/x/tools/gopls).
