### ISSUE TITLE
add support for "autobuild" (as in nsf/gocode)

### ISSUE THREAD

**Issue by glepnir** [mdempsky/gocode#94]
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?
`go version  1.11.2`
### What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/menahem/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/menahem/workspace"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build061186512=/tmp/go-build -gno-record-gcc-switches"
```

### What is the debug output of `gocode`?
![2018-12-06 14-26-34](https://user-images.githubusercontent.com/41671631/49565693-05d93680-f963-11e8-9e68-59d3813d0501.png)

```
// Package main provides ...
package main

import (
	"test/db"
	"fmt"
)

func main() {
	db.#
}

2018/12/06 14:12:04 -------------------------------------------------------
2018/12/06 14:12:04 Error parsing input file (outer block):
2018/12/06 14:12:04  /home/menahem/workspace/src/test/main.go:10:5: expected selector or type assertion, found ';'
2018/12/06 14:12:04 gbimporter: no package found for test/db: can't find import: "test/db"
2018/12/06 14:12:04 Elapsed duration: 1.200777ms
2018/12/06 14:12:04 Offset: 0
2018/12/06 14:12:04 Number of candidates found: 0
2018/12/06 14:12:04 Candidates are:
2018/12/06 14:12:04 =======================================================
```

### What (client-side) flags are you passing into `gocode`?
I set `gocode -source`

### What editor are using?
vim

**Comment by glepnir** [comment]
In the nsf/gocode version I can set `autobuild` to true to complete the completion of the reference package, but in this version of gocode, how do I need to set it up? `-source`?

**Comment by stamblerre** [comment]
`-source` causes everything to be type-checked from source. Where are you setting this flag? It will need to be set on the client side, so it will have to be configured differently depending on your editor (in VSCode, there is a setting called `go.gocodeFlags`.

Otherwise, you will need to build your package. You may need to use the `-i` flag with `go install`. You should end up with a file `$GOPATH/pkg/linux_amd64/test/db.a`, which is what gocode is looking for.

**Comment by Menahem1227** [comment]
> `-source`导致所有内容都从源代码进行类型检查。你在哪里设置这面旗帜？它需要在客户端设置，因此必须根据您的编辑器进行不同的配置（在VSCode中，有一个名为的设置）`go.gocodeFlags`。
> 
> 否则，您将需要构建您的包。您可能需要使用`-i`标记`go install`。你应该得到一个文件`$GOPATH/pkg/linux_amd64/test/db.a`，这是gocode正在寻找的。


I also found this problem, set `autobuild` will generate a `.a `file under pkg for gocode search, this version of gocode I did not find such a setting,` -i`this flag will generate a .a package in real time to call gocode ？

**Comment by glepnir** [comment]
I use the vim ，completion plugin to use deoplete, set `let g:deoplete#sources#go#source_importer = 1`, it starts working, can complete the completion of the local package, but it is slow,   on my mac `go version 1.10.4`， I am using `nsf/gocode` which is very handy for me. By setting` autobuild `to `true`,  can complete the completion of the local package. The speed is very fast. I think `mdempksky/gocode` should not remove `autobuild`. Here I did a test and you can find that `mdemosky/gocode` is very slow.Another problem is `nsf/gocode`, which can prompt me for the standard library, but `mdempsky/gocode` does not prompt the standard library.
This is in linux  `go version 1.11.2` `mdemosky/gocode`
![sceenshot](https://user-images.githubusercontent.com/41671631/49681998-6e9cec00-fae6-11e8-9b73-ea2d76b59924.gif)
This is in mac  `go version 1.10.4 ` `nsf/gocode`
![sceenshot1](https://user-images.githubusercontent.com/41671631/49682003-912f0500-fae6-11e8-9d30-287b1eddc45a.gif)

**Comment by glepnir** [comment]
On the mac it is done by finding the .a file, the speed is very fast, but after I set up the souce in linux, I found that it did not generate the .a file under pkg, is it for this reason it is slowly?
On mac
![3](https://user-images.githubusercontent.com/41671631/49775415-21fa2080-fd33-11e8-91f6-87e11fabf694.png)
On linux
![2](https://user-images.githubusercontent.com/41671631/49775421-26263e00-fd33-11e8-94b7-19ed2fc6106c.png)

**Comment by stamblerre** [comment]
Yes, but `-source` type-checks everything from source, so it's expected to be slow. For optimal speed, you should not use `-source`. 

When you build your project, you can generate the `.a` file by building your project with `-i` flag (https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies).

**Comment by glepnir** [comment]
@stamblerre  Do i have to manually generate the` .a` file with the `-i `tag each time? Obviously this is very unreasonable, the package may need to be changed several times, can it be automatically generated by the `.a` file when I save it to look for `gocode`, there is `autobuild` option I just set `true`, under any circumstances I There is no need to generate a` .a `file, it will be generated automatically after saving. And the speed of use is also very fast,

**Comment by stamblerre** [comment]
As long as you are not changing the names or types of exported symbols in your dependency package, you won't need to regenerate the `.a` files. Once the `.a` file is there, gocode will be able to find it, even if it is a little out of date.

This version of gocode isn't under active development, so I have no plans to add support for autobuild, especially since many editors already rebuild on save by default. I'm always willing to accept PRs however.

**Comment by glepnir** [comment]
> 只要您不更改依赖包中的导出符号的名称或类型，就不需要重新生成`.a`文件。一旦`.a`文件存在，gocode就能找到它，即使它有点过时了。
> 
> 这个版本的gocode没有正在开发中，所以我没有计划添加对autobuild的支持，特别是因为许多编辑器默认情况下已经在save上重建了。但我总是愿意接受PR。

@stamblerre  It worked successfully, but I need to go install every time I finish writing a package. This is very bad for me. For me, I think it needs to be done by go tools. I don't need it. I care about it, if I change some methods or variables in the package, etc. I need to rebuild the .a file. Can I add new support?

**Comment by stamblerre** [comment]
I'm happy to review any PRs to add the autobuild feature. I'll change the title of this issue to reflect that.

**Comment by glepnir** [comment]
> I'm happy to review any PRs to add the autobuild feature. I'll change the title of this issue to reflect that.

thanks

**Comment by zaquestion** [comment]
@stamblerre Could you offer any guidance on implementation? It sorta looks like this should be implemented in `internal/cache` or `internal/suggest`, this fork has diverged quite a bit from the original, so its hard to map up too the `nsf/gocode` implementation.

**Comment by stamblerre** [comment]
@zaquestion:

I think the key code should be in [this function](https://github.com/nsf/gocode/blob/9d1e0378d35b0527c9aef0d17c0913fc38d88b81/declcache.go#L192) and [this command](https://github.com/nsf/gocode/blob/9d1e0378d35b0527c9aef0d17c0913fc38d88b81/declcache.go#L241).

It's easier to see in the cache importer, which directly uses the `gcexpordata.Find` function [here](https://github.com/mdempsky/gocode/blob/be056ad32a5e9e6b0f640e650319100c464e19a7/internal/cache/importer.go#L94). If the filename is empty, we could then run `go install` for that package, recreating the `.a` file. In gbimporter, it's a little trickier because it `go/build` uses the `gcexportdata.Find` function under the hood, but we could still test this case by using it explicitly in gocode as well.

Hope that helps - let me know if you have more questions.

**Comment by glepnir** [comment]
@stamblerre Recently tried to use lsp, I found that` bingo` and `go-langserver` completion and jump and other functions are very good, I am very glad to hear that you are developing `golsp`, is there any need to use` gocode`?

**Comment by stamblerre** [comment]
@PendragonSaber: Once golsp is released (we will announce when it is ready), then gocode will no longer be necessary. In the meantime, I am maintaining gocode.

**Comment by glepnir** [comment]
> @PendragonSaber：一旦golsp被释放（我们将在它准备好时宣布），那么将不再需要gocode。与此同时，我正在维护gocode。

Looking forward to using golsp, it is best to download it for Chinese users. We can't access golang.org normally. The current experience of gocode is not friendly.
